version: '3.8'
services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_DATABASE=users
      - MARIADB_USER=jonan
      - MARIADB_PASSWORD=test
      - MARIADB_ROOT_PASSWORD=p132
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pp132"] # Check if database is healthy
    profiles:
      - backend

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=videogames_lists
    profiles:
      - backend

  users-api:
    build: ./users-backend
    depends_on:
      mariadb:
        condition: service_healthy
    profiles:
      - backend

  videogames-api:
    build: ./videogames-backend
    depends_on:
      - mongo
    profiles:
      - backend

  gateway:
    build: ./gateway
    ports:
      - 80:80
    depends_on:
      - users-api
      - videogames-api
    profiles:
      - backend

  web:
    build: ./frontend
    ports:
      - 3000:3000
    profiles:
      - frontend


networks:
  myvideogamesxp: